services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nour
    ports:
      - "3060:3060"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data